### ISSUE TITLE
handle confluence upgrades smoothly

### ISSUE THREAD

**Issue by mkrakowitzer** [mkrakowitzer/puppet-confluence#6]
Ad support for upgrading confluence module smoothly via the module, as we do in the jira and stash modules.

**Comment by chihoko** [comment]
What would be the recommended way to handle upgrades before this class is released? I would assume incrementing the version number in the manifest and running the standard installer/wizard?

**Comment by mkrakowitzer** [comment]
You can just stop confluence, increment the version number, run puppet.
